
merge_gold:

  inputs:
    equities:
      enabled: true
      path: silver/equities.parquet

    equities_daily:
      enabled: true
      path: silver/equities_daily.parquet

    macro:
      enabled: false
      path: silver/macro.parquet

    weather:
      enabled: true
      path: silver/weather.parquet

  merge:
    anchor: equities
    how: left

    dropna_target: true
    target_cols:
      - log_rv_xle

    start_date: null
    end_date: null

    enforce_lags_only: true

    prefixes:
      equities_daily: etf_
      macro: macro_
      weather: wx_

  postprocess:
    drop_cols: []

  output:
    store_path: gold/modeling_table.parquet
