storage:
  backend: local
  base_dir: data

steps:
  ingestion:
    enabled: false
    config: configs/steps/ingest.yaml

  features:
    enabled: false
    config: configs/steps/build_features.yaml

  merge:
    enabled: false
    config: configs/steps/merge.yaml

  prediction:
    enabled: true
    config: configs/steps/prediction.yaml
