storage:
  backend: local
  base_dir: data

steps:
  ingestion:
    enabled: true
    config: steps/ingest.yaml

  features:
    enabled: true
    config: steps/build_features.yaml

  merge:
    enabled: true
    config: steps/merge.yaml

  prediction:
    enabled: true
    config: steps/prediction.yaml
