storage:
  backend: s3
  bucket: volatility-project
  prefix: 
  region: us-east-2

steps:
  ingestion:
    enabled: true
    config: configs/steps/ingest.yaml

  features:
    enabled: true
    config: configs/steps/build_features.yaml

  merge:
    enabled: true
    config: configs/steps/merge.yaml
    
  prediction:
    enabled: true
    config: configs/steps/prediction.yaml